# Introductory applied machine learning (INFR10069)

# Lab 0: Introduction

To complete this lab you should:

* Set up your IAML environment ready for the course (see [README](https://github.com/uoe-iaml/iaml-labs))
* __Read the text__ and run all the cells in this notebook and have a play with all the objects created (Don't worry about messing up this notebook - you can always download another copy!)
* __Attempt all the Exercises at the bottom of the notebook__

# Setting up

Instructions for setting up can be found in the GitHub project [README](https://github.com/uoe-iaml/iaml-labs). Please follow the instructions to the letter, then start a jupyter server and open this file to get started:

```{bash}
source activate py3iaml
jupyter notebook
# Your browser should open, navigate to this file and open it
```

# Introducing main packages

In the following sections we introduce the main **packages** we will be using in this course. If you think that you are already familiar with them, please feel free to skip to the excercises at the end of this notebook.

The packages that we will use are the following:
* [numpy](http://www.numpy.org/): scientific computing by using array objects


* [pandas](http://pandas.pydata.org/): data structures and data analysis tools


* [matplotlib](http://matplotlib.org/): plotting library (similar to MATLAB's plot interface)


* [seaborn](https://seaborn.github.io/index.html): data visualisation library which works on top of matplotlib

Throughout the course, we will also make heavy use of [scikit-learn](http://scikit-learn.org/0.19/) which is a machine learning library implementing many learning algorithms and useful tools. This is introduced in Lab 2.

## IPython / Jupyter environment ======

Basic knowledge of `python` is assumed for this course. If you haven't used python before, you are strongly advised to familiarise yourselves with basic python syntax and working in the Jupyter environment. There are many excellent tutorials available on the web and you can choose the ones you like the most. If you are not sure which ones to choose, these are good starting points:

[Introduction to Python for scientific computing](http://bebi103.caltech.edu/2015/tutorials/t1a_intro_to_python.html)

[Introduction to Jupyter notebooks](http://bebi103.caltech.edu/2015/tutorials/t0b_intro_to_jupyter_notebooks.html)

[Python/Numpy tutorial](http://cs231n.github.io/python-numpy-tutorial/#python)
(A large part of Lab 1 is based on this tutorial)

**IMPORTANT**

All labs and assignments will be done in Jupyter Notebooks, so do ask questions if you're struggling.

### Basic operation and shortcuts

There are two modes of selection when inside a Jupyter Notebook:
    1. Command Mode - When you hit up/down arrows you select different cells. Hit enter to enter edit mode.
    1. Edit Mode - You can edit the cell. Hit Esc to enter Command Mode again.

In Command Mode (cell highlighted blue):
```
                h - bring up help window (contains full list of shortcuts!)
          <enter> - Enter Edit Mode
                a - create new cell above selected
                b - create cell below selected
             d, d - delete selected cell
```

In Edit Mode (cell highlighted green):
```
            <esc> - Enter Command Mode
<shift> + <enter> - Run cell and move to cell below in Command Mode
 <ctrl> + <enter> - Run cell in place

```

### Printing and cell output

A Jupyter notebook is a collection of code and text cells. Each code cell can be run and the output is given below the cell. A number appears at the side of the cell to indicate the order in which the cells were run. 

All objects created by running cells are stored in the kernel running in the background. You can restart the kernel by using the Kernel menu at the top of the notebook.

You'll notice that the notebook will try to display the last thing in the cell, even if you don't use a print statement. However, if you want to print multiple things from one cell, you need to use multiple print statements (or multiple cells).

In [1]:
a = 1
b = 2
a

1

In [2]:
a
b

2

In [3]:
print(a)
print(b)

1
2


### Connecting to the Kernel

Sometimes we might want to connect to the same notebook kernel from multiple frontends. This is useful for excecuting quick calculations, or checking objects currently stored in the kernel, without having to create a new cell in the notebook.

The `%connect_info` line magic displays the information necessary to connect another frontend to the Notebook kernel.

In [4]:
%connect_info

{
  "shell_port": 52023,
  "iopub_port": 52024,
  "stdin_port": 52025,
  "control_port": 52027,
  "hb_port": 52026,
  "ip": "127.0.0.1",
  "key": "4a020b32-f4706022a05892d2cdb2bb7a",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": ""
}

Paste the above JSON into a file, and connect with:
    $> jupyter <app> --existing <file>
or, if you are local, you can connect with just:
    $> jupyter <app> --existing kernel-ec4bd7c2-c1b6-4f3a-9592-552ffcd9d37a.json
or even just:
    $> jupyter <app> --existing
if this is the most recent Jupyter kernel you have started.


For example, if this is the only kernel you have started, go to your terminal and execute:

* `jupyter console --existing` 

This will bring up a console that is connected to the same kernel as this notebook. This can be handy if you want to do some exploration of objects without creating new cells in the workbook.

#### **WARNING**

If you connect to a kernel via the console, be careful you do not kill the kernel when quitting the console. You must use:

* `<ctrl> + d`
* or `exit(keep_kernel=True)`

### Built-in magic commands

There are [many built-in magic commands](http://ipython.readthedocs.io/en/stable/interactive/magics.html) (like `%connect_info`) which allow you to do other fun things with notebooks. Check them out.

### Tab completion

Tab completion is a powerful method for viewing object attributes and available methods.

Let's see an example of this by using a Python [list](http://www.tutorialspoint.com/python/python_lists.htm). We will create a list and then you can see what methods are available by typing the list name followed by `.` and then hitting the &lt;tab&gt; key. Then you can access any method's help documentation by hitting the method's name followed by `?`; this opens a 'pager' at the bottom of the screen, you can hit &lt;esc&gt; to exit it.

In [5]:
l = [1, 4.2, 'hello']
l

[1, 4.2, 'hello']

In [6]:
# type l. then hit <tab>

In [7]:
l.append?

## Import packages

It's generally good practice to import all your packages at the top of a file. We will do so in future tutorials.

Before we start, we need to import the packages that we will be using later. If you are having trouble importing any of these packages make sure that these are properly installed. If you still encounter issues, refer to Installing instructions.

In [8]:
import os
import sys
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

## Numpy introduction =======

Numpy is a powerful scientific computing library. The fundmental object is the (n-dimensional) numpy array and the library provides a collection of tools for working with such arrays. If you are already familiar with MATLAB you might find this [tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/numpy-for-matlab-users.html) useful. 

The following Numpy introduction is largely based on this [tutorial](http://cs231n.github.io/python-numpy-tutorial/#numpy).

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a [tuple](http://www.tutorialspoint.com/python/python_tuples.htm) of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension. *N.B. this use of the word 'rank' is not the same as the meaning in linear algebra.*

We can initialize numpy arrays from nested Python [lists](http://www.tutorialspoint.com/python/python_lists.htm), and access elements using square brackets:

In [ ]:
import numpy as np
a = np.array([1, 2, 3])  # Creates a rank 1 array (i.e. vector)
a

In [ ]:
type(a)  # Prints the type of object a (array)

In [ ]:
a.shape  # Prints the number of elements for each dimension

In [ ]:
print(a[0], a[1], a[2], a[-1], a[-2], a[-3])  # Select array elements by index (starts at 0)

In [ ]:
try:
    a[3]  # Will error
except IndexError as e:
    print('{}'.format(e))
except:
    print("Unexpected error:", sys.exc_info()[0])
    raise

In [ ]:
a[0] = 5  # Change an element of the array

In [ ]:
a

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
b

In [ ]:
b.shape          

In [ ]:
print(b[0, 0], b[0, 1], b[1, 0]) 

N.B. Python follows [0-based indexing](https://en.wikipedia.org/wiki/Zero-based_numbering) (as opposed to MATLAB which follows 1-based indexing).

### Creating arrays

We have many options here:

#### Set matrix types

Generally the first argument is simply the shape of the resulting array

In [ ]:
np.zeros((2, 2))

In [ ]:
np.ones((1, 2))

In [ ]:
np.full((2, 2), 7)

In [ ]:
np.eye(2)

In [ ]:
np.random.random((2, 2))

In [ ]:
mu = 2
sigma = .2
np.random.normal(mu, sigma, (4,1)), np.random.normal(mu, sigma, 10)

#### From a list

In [ ]:
some_list = [1, 4, 6, 8]
e = np.array(some_list)
e

In [ ]:
some_list = [[1, 4, 6, 8], [2, 2, 4, 4]]
f = np.array(some_list, dtype=float)
f

#### Appending an existing array

In [ ]:
g = np.array([])
for ii in range(10):
    g = np.append(g, ii)
g

Be careful with types though, numpy will do some inference on your behalf...it may not be what you want/intended.

In [ ]:
np.append(g, 'hello')

In [ ]:
e.dtype

In [ ]:
np.append(e, 2.0)

In [ ]:
np.append(e, 2.0).dtype

### Array indexing

Slicing is the most common way to index arrays. This works in a similar way to indexing python lists. 

There are also other options, such as integer and boolean array indexing.

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

In [ ]:
b = a[:2, 1:3]
b

In [ ]:
a[0, 1]

A slice of an array is a view into the same data, so modifying it will modify the original array. For example: b[0, 0] is the same piece of data as a[0, 1]. Modifying b will modify a.

In [ ]:
b[0, 0] = 77
a[0, 1]

We can also index particular entries based on some function, which we generally call masking. For example, we may want to zero out all even entries. To do so, we can do the following:

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) # Reinitialise a
a[a%2 == 0] = 0
a

Basically, the above can be interpeted as follows: ```a%2 == 0``` creates a boolean matrix of the same size as a where the entries are True/False depending on whether the corresponding entry in a is even or false (% is the modulus operator). Let us call this ```a_index```. Then we use this to index into the original a by ```a[a_index]``` and setting all such entries to 0. If we know the size of the indexing, then we can also do something more fancy such as:

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]], dtype=float) # Reinitialise a (enforce type float: see below)
a[a%2 == 0] = np.random.random((6))
a

Going back to the issue of views. Note that b still points to the original matrix a and not the ones we just created: i.e. when we reassigned a to the new values, (```a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])```), we are only changing where a points... b still points to the original data.

In [ ]:
b

### Array datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
x.dtype     

In [ ]:
x = np.array([1.0, 2.0])  # Let numpy choose the datatype
x.dtype         

In [ ]:
x = np.array([1, 2], dtype=np.int64)  # Force a particular datatype
x.dtype            

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
x

In [ ]:
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
y

#### Elementwise sum, equivalent expressions:

In [ ]:
x + y

In [ ]:
np.add(x, y)

#### Elementwise difference, equivalent expressions:

In [ ]:
x - y

In [ ]:
np.subtract(x, y)

#### Elementwise product, equivalent expressions:

In [ ]:
x * y

In [ ]:
np.multiply(x, y)

#### Elementwise division, equivalent expressions:

In [ ]:
x / y

In [ ]:
np.divide(x, y)

#### Elementwise square root

In [ ]:
np.sqrt(x)

#### Dot product and matrix multiplicaiton

Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the `np.dot` function or `.dot` method to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `dot` is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

##### Inner product of vectors

In [ ]:
np.dot(v, w)

##### Matrix vector product

In [ ]:
x.dot(v)  # using x's method

In [ ]:
np.dot(x, v)  # using the numpy function

##### Matrix matrix product

In [ ]:
x.dot(y)  # using x's method

In [ ]:
np.dot(x, y)  # using the numpy function

### Mathematical functions

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1, 2], [3, 4]])
x

In [ ]:
np.sum(x)  # Compute sum of all elements

In [ ]:
np.sum(x, axis=0)  # Compute sum of each column - sum *over rows* i.e. dimension 0

In [ ]:
np.sum(x, axis=1)  # Compute sum of each row - sum *over columns* i.e. dimension 1

You can find the full list of mathematical functions provided by numpy in the [documentation](https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.math.html).


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the `T` attribute of an array object:

In [ ]:
x = np.arange(4).reshape((2, 2))
x

In [ ]:
x.T

In [ ]:
np.transpose(x) # Equivalent expression

In [ ]:
# Note that taking the transpose of a rank 1 array (a vector) does nothing:
v = np.array([1, 2, 3])
v

In [ ]:
v.T

In [ ]:
x.reshape((4, 1))

In [ ]:
x.reshape((4,))

In [ ]:
y = np.arange(27).reshape((3, 3, 3))
y

In [ ]:
y.shape

In [ ]:
y.reshape((3, -1))

In [ ]:
y.reshape((3, -1)).shape

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. 

In [ ]:
x = np.arange(12).reshape((4, 3))
x

In [ ]:
v = np.array([1, 0, 1])
v

In [ ]:
x + v  # Add v to each row of x using broadcasting

`x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

* If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
* The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
* The arrays can be broadcast together if they are compatible in all dimensions.
* After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
* In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.

So be careful with shapes...

In [ ]:
y = x.T
y

In [ ]:
try:
    y + v  # Add v to each column of y using broadcasting...?
except ValueError as e:
    print(e)
except:
    print("Unexpected error:", sys.exc_info()[0])
    raise

And especially careful with vectors!

In [ ]:
try:
    y + v.T  # Add v to each column of y using broadcasting...?
except ValueError as e:
    print(e)
except:
    print("Unexpected error:", sys.exc_info()[0])
    raise

In [ ]:
y + v.reshape((3, 1))  # Add v to each column of y using broadcasting!

In [ ]:
print('x shape:', x.shape)
print('v shape:', v.shape)
print('y shape:', y.shape)

### Numpy documentation

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/) to find out much more about numpy.

## ======= Pandas introduction  =======

Pandas is a library for data manipulation and analysis. There are two fundamental data structures in pandas: the **Series** and **DataFrame** structures which are built on top of NumPy arrays.

The following introduction is largely based on this [tutorial](http://www.gregreda.com/2013/10/26/intro-to-pandas-data-structures/). Another useful referece is the [Pandas introduction to data structures](http://pandas.pydata.org/pandas-docs/version/0.23.4/dsintro.html). Pandas is well documented and you will find good information about all methods and structures in the [API reference](http://pandas.pydata.org/pandas-docs/version/0.23.4/api.html)

### Series

A **Series** a one-dimensional object (similar to a vector). Each element has a corresponding *index*. By default the indices range from 0 to N, where N is the length of the Series.

In [ ]:
# Let's create a Series by passing in a list without specifying the indices.
s = pd.Series([1, 4.2, 'Hello'])
s

In [ ]:
# Now, let's specify the indices explicitly
s = pd.Series([1, 4.2, 'Hello'], index=['A', 'B', 'C'])
s

In [ ]:
# Indexing the Series
s['B']

In [ ]:
# We can also index by using boolean logic (much like masking)
s = pd.Series([1, 4.2, 0.5, 3, 5.6], index=['A', 'B', 'C', 'D', 'E'])
s[s > 2]

### DataFrame

A DataFrame is a tabular data structure comprised of rows and columns. You can also think of the DataFrame as a collection of Series objects that share an index. 

#### Creating DataFrame structures

We can create an empty DataFrame by specifying the column names. Then we can insert data row by row.

In [ ]:
df = pd.DataFrame(columns=['Gender', 'Age', 'Height', 'Weight'])
df

In [ ]:
# Now let's add an observation
df.loc[0] = ['Male', 23, 180, 73]  # Note how we used .loc to specify the index
df.loc['A'] = ['Female', 27, 167, 59]
df

You can populate using a dictionary too which allows you to do things in a nonstandard order...

In [ ]:
df.loc['i'] = dict(Weight='3kgs', Age=10, Gender='Blue', Height=-12)
df

#### Creating DataFrame from other structures

You can also create a dataframe from:
* Dict of 1D ndarrays, lists, dicts, or Series
* 2-D numpy.ndarray
* Structured or record ndarray
* A Series
* Another DataFrame

For example:

In [ ]:
# Create a DataFrame from a list
some_list = [['Male', 23, 180, 73], ['Female', 27, 167, 59]]
df = pd.DataFrame(some_list, index=[0, 'A'], columns=['Gender', 'Age', 'Height', 'Weight'])
df

In [ ]:
# Create a DataFrame from a dictionary where keys are column values
column_key_dict = {
    'Gender': ['Male', 'Female'],
    'Age': [23, 27],
    'Height': [180, 167],
    'Weight': [73, 59]
}
df = pd.DataFrame.from_dict(column_key_dict, orient='columns')
df.index = [0, 'A']
df

In [ ]:
# Create a DataFrame from a dictionary where keys are index values
index_key_dict = {0:['Male', 23, 180, 73], 'A':['Female', 27, 167, 59]}
df = pd.DataFrame.from_dict(index_key_dict, orient='index')
df.columns = ['Gender', 'Age', 'Height', 'Weight']
df

In [ ]:
# Using the DataFrame call, keys are assumed to be column headers
df = pd.DataFrame({0:['Male', 23, 180, 73], 'A':['Female', 27, 167, 59]}, 
                   index=['Gender', 'Age', 'Height', 'Weight'])
df

We can also transpose using the `.T` method

In [ ]:
df = df.T
df

#### Loading a CSV into a DataFrame

Most commonly we create DataFrame structures by reading csv files. To run the following piece of code you will need the datasets associated with the course: these should have been downloaded with the code, and will exist adjacent to this notebook (i.e. within the `Labs` sub-directory):

In [ ]:
cpu_loc = os.path.join(os.getcwd(), 'datasets', 'cpu.csv')
cpu_loc

In [ ]:
cpu = pd.read_csv(cpu_loc)
cpu.head() # Head shows the first few elements (unless specified otherwise) of the DataFrame

You should see that each observation in our dataset comprises 8 measurements (attributes).

#### Basic methods for DataFrame objects
* `head(N)`: displays the first N elements of the DataFrame
* `tail(N)`: displays the last N elements of the DataFrame
* `info()`:  displays basic information about the variables
* `describe()`: displays summary statistics of the data

Execute the following cells and observe the outputs.

In [ ]:
cpu.tail(5)

In [ ]:
cpu.info()

In [ ]:
cpu.describe()

#### Column Selection

You can think of a DataFrame as a group of Series that share an index (in this case the column headers). This makes it easy to select specific **columns**.

In [ ]:
cpu['MMAX'].head(5)

In [ ]:
type(cpu['MMAX'])

To select multiple columns we simply need to pass a list of column names. The resulting object is another DataFrame.

In [ ]:
cpu[['MMIN', 'MMAX']].head(7)

In [ ]:
type(cpu[['MMIN', 'MMAX']].head(7)) # This is a DataFrame

#### Row selection

To select specific **observations (i.e. rows)** we need to pass in the corresponding indices. This operation is called *slicing*. The resulting structure is again a DataFrame.

In [ ]:
cpu[0:3]

In [ ]:
# This is equivalent to using .iloc
cpu.iloc[0:3]

#### Filtering

Now suppose that you want to select all the observations which have an MMAX value which is higher than 35000. It is easy to do that:

In [ ]:
cpu[cpu['MMAX'] > 35000]

Or equivalently:

In [ ]:
cpu[cpu.MMAX > 35000]

Note that the concept is similar to the 'masking' we described for numpy arrays. You can also filter the data by using multiple attributes:

In [ ]:
cpu[(cpu.MMAX > 35000) & (cpu.MMIN > 16000)]

We saw before how we can select rows by passing the index numbers. This most of the time works but very often our indices are not in linear ascending order. 

There are two basic methods of indexing DataFrame structures:
* `loc`: works on labels in the index
* `iloc`: works on the position in the index (so it only takes integers)

Indeed, it is often safest to use the above methods (rather than just using square brackets as we have done above) to index into pandas dataframes. The following example should clarify the difference between label-based indexing (`loc`) and positional indexing (`iloc`)


In [ ]:
# First let's create a new dataframe
cpu_new = cpu[cpu['MMAX'] > 35000]
cpu_new

In [ ]:
cpu_new.loc[8:10] # Looks for the rows which are labelled 8 and 9

Note that we can also index into columns using `loc`, we just have to specify the second dimension (much like what we would do with numpy arrays):

In [ ]:
cpu_new.loc[:, 'CACH']

In [ ]:
cpu_new.iloc[0:2] # Look for the first and second rows (this yields the same result as before)

In [ ]:
cpu_new.iloc[:, 4] # And now using column indexing

In [ ]:
# If we try the following we will get an empty DataFrame because there are no rows with labels 0 and 1.
cpu_new.loc[0:2]

In [ ]:
# The result is always a DataFrame
type(cpu[0:2])

A very common scenario will be the following. We want to select specific observations and columns of a DataFrame and convert to a NumPy array so that we can use it for feature extraction, classification etc. This can be achieved by using the `values` property (for an explanation of properties as opposed to methods, refer to [this](https://stackoverflow.com/questions/7374748/whats-the-difference-between-a-python-property-and-attribute)).

In [ ]:
# Select the first 10 observations and the "MMIN" and "MMAX" columns only and convert to numpy array.
cpu[:10][['MMIN', 'MMAX']].values

You can confirm that by using the `values` method the resulting object is a NumPy array.

#### A Further note on Indexing

*WARNING* - indexing is probably the most difficult part of pandas to get used to. If you get stuck [refer to the documentation on indexing](http://pandas.pydata.org/pandas-docs/version/0.23.4/indexing.html).


Summary of DataFrame methods for indexing:
* iloc - ignore index labels, index like numpy with integer positions
* loc - use index labels


To illustrate, observe what happens when we reorder the rows of our dataframe.

In [ ]:
cpu.sort_values('ERP', inplace=True)

In [ ]:
cpu.iloc[:10]

In [ ]:
cpu.loc[:10]

Observe what happens if we change the label of one of the now first index

In [ ]:
cpu = cpu.rename(index={cpu.index[0]: 'A'})

In [ ]:
cpu.iloc[:10]

In [ ]:
try:
    cpu.loc[:10]
except TypeError as e:
    print(e)

For more, check out [Advanced Indexing](http://pandas.pydata.org/pandas-docs/version/0.23.4/advanced.html)

## Matplotlib introduction

Matplotlib is a 2D python plotting library with a similar interface to MATLAB's plot engine. The library is fully compatible with NumPy which means that we can -and most of the times will- pass numpy arrays as input arguments to the various plotting functions.

There are many [resources](http://matplotlib.org/resources/index.html) for learning how to use Matplotlib. The following examples demonstrate only some basic plotting functions. When you are looking for a particular feature which you don't know yet how to implement a web search can prove very useful.

In [ ]:
# The first example creates a sine and a cosine and plots them.
X = np.linspace(-np.pi, np.pi, 256,endpoint=True) # Evenly spaced numbers over the specified interval
C, S = np.cos(X), np.sin(X) # Create a sine (S) and a cosine (C)

plt.figure(figsize=(8,5)) # Instantiates figure with a specified size
plt.plot(X,C, label='Cosine')
plt.plot(X,S, label='Sine')
plt.legend() # Displays legend
plt.show()

In [ ]:
# Create 4 subplots and plot cosines with different colours, linestyels and linewidths.
X = np.linspace(-np.pi, np.pi, 256,endpoint=True) # Evenly spaced numbers over the specified interval
C1, C2, C3, C4 = np.cos(X), np.cos(X+0.5), np.cos(X+1.), np.cos(X+1.5)

fig, ax = plt.subplots(figsize=(7,7))
plt.subplot(2,2,1)
plt.plot(X, C1)
plt.title('C1')
plt.xticks([]) # Removes xticks
plt.subplot(2,2,2)
plt.plot(X, C2, color='green',  linestyle='-.')
plt.title('C2')
plt.xticks([]) # Removes xticks
plt.yticks([]) # Removes yticks
plt.subplot(2,2,3)
plt.plot(X, C3, color='k', linestyle='--')
plt.title('C3')
plt.subplot(2,2,4)
plt.plot(X, C4, color='m', linewidth = 5.)
plt.title('C4')
plt.yticks([]) # Removes yticks
plt.show()

Another way to reference subplots is using the Axes objects. This code acheives the same thing as above but, instead of using the package api functions, it uses the Axes object methods:

In [ ]:
fig, ax = plt.subplots(2, 2, figsize=(7,7), sharex=True, sharey=True)
# ax is a 2 x 2 numpy array at this point containing the Axes objects
ax = ax.flatten()  # this simply flattens the array such that we can reference by a single index
ax[0].plot(X, C1)
ax[0].set_title('C1')
ax[1].plot(X, C2, color='green',  linestyle='-.')
ax[1].set_title('C2')
ax[2].plot(X, C3, color='k', linestyle='--')
ax[2].set_title('C3')
ax[3].plot(X, C4, color='m', linewidth = 5.)
ax[3].set_title('C4')
plt.show()

**N.B. Because we created the subplots up front and stated the axes should be the same, matplotlib intelligently labels the axes for us**

In [ ]:
# Plot a histogram and add some text
mu, sigma = 100, 15
x = mu + sigma * np.random.randn(10000) # Generate data from a normal distribution with mean mu and variance sigma

# the histogram of the data
n, bins, patches = plt.hist(x, 50, density=True, facecolor='g', alpha=0.75)

plt.xlabel('Smarts')
plt.ylabel('Probability')
plt.title('Histogram of IQ')
plt.text(60, .025, r'$\mu=100,\ \sigma=15$') # Adds some text by using TeX
plt.axis([40, 160, 0, 0.03]) # Sets the axes limits
plt.grid(True) # Enables grid
plt.show()

## Seaborn

[Seaborn](https://seaborn.github.io/index.html) is a visualisation library built on top of matplotlib which offers some aesthetic enhancement and, more importantly, provides some high-level functions for  "exploring and understanding data". Seaborn is also tightly integrated with pandas and provides support for both numpy and pandas data structures.

### Aesthetics

Firstly note that when you import and use seaborn, it may change the aesthetics of all matplotlib plots you make subsequently. If you only ever want to use matplotlib defaults, you can import seaborn like this: `import seaborn.apionly as sns`. 

To reset to matplotlib defaults, use: `sns.reset_defaults()`

There's some really useful stuff you can do with seaborn, especially with respect to setting default sizings with respect to the context in which you're producing plots. With one function, seaborn can make plots appropriate for posters, papers, notebooks, or talks. For further information see the [seaborn documentation on aesthetics](https://seaborn.pydata.org/tutorial/aesthetics.html)

### Seaborn implemented functions [Optional]
The Seaborn website has many great examples. Below we show a few taken directly from the website. These are just to give you a flavour of the kinds of things that Seaborn can do. You can use it as reference later; by no means should you learn this code by heart! You should definitely not worry if some of the following commands do not make sense just yet.

In [ ]:
# Load the example titanic dataset
df = sns.load_dataset("titanic")

Let us first see how Seaborn can render the same visualisation in different formats, depending on intended medium (*ignore any warnings that come up*):

In [ ]:
# Make a custom palette with gendered colors
pal = {"male":"#6495ED", "female": "#F08080"}

with sns.axes_style(style="darkgrid"):
    for context in ['notebook', 'paper', 'poster', 'talk']:
        with sns.plotting_context(context):
            # Show the survival proability as a function of age and sex
            g = sns.lmplot(x="age", y="survived", col="sex", hue="sex", data=df,
                           palette=pal, y_jitter=.02, logistic=True)
            g.set(xlim=(0, 80), ylim=(-.05, 1.05))
            plt.show()

In [ ]:
# using a with statement means style defaults are not overridden
with sns.axes_style(style="white", rc=dict(palette="muted", color_codes=True)):
    rs = np.random.RandomState(10)

    # Set up the matplotlib figure
    f, axes = plt.subplots(2, 2, figsize=(7, 7), sharex=True)
    sns.despine(left=True)

    # Generate a random univariate dataset
    d = rs.normal(size=100)

    # Plot a simple histogram with binsize determined automatically
    sns.distplot(d, kde=False, color="b", ax=axes[0, 0])

    # Plot a kernel density estimate and rug plot
    sns.distplot(d, hist=False, rug=True, color="r", ax=axes[0, 1])

    # Plot a filled kernel density estimate
    sns.distplot(d, hist=False, color="g", kde_kws={"shade": True}, ax=axes[1, 0])

    # Plot a historgram and kernel density estimate
    sns.distplot(d, color="m", ax=axes[1, 1])

    plt.setp(axes, yticks=[])
    plt.tight_layout()
    plt.show()

In [ ]:
with sns.axes_style(style="white"):

    # Generate a random correlated bivariate dataset
    rs = np.random.RandomState(5)
    mean = [0, 0]
    cov = [(1, .5), (.5, 1)]
    x1, x2 = rs.multivariate_normal(mean, cov, 500).T
    x1 = pd.Series(x1, name="$X_1$")
    x2 = pd.Series(x2, name="$X_2$")

    # Show the joint distribution using kernel density estimation
    g = sns.jointplot(x1, x2, kind="kde", height=7, space=0)
    plt.show()

In [ ]:
with sns.axes_style(style="whitegrid", rc=dict(palette="pastel", color_codes=True)):
    # Load the example tips dataset
    tips = sns.load_dataset("tips")

    # Draw a nested violinplot and split the violins for easier comparison
    sns.violinplot(x="day", y="total_bill", hue="sex", data=tips, split=True,
                   inner="quart", palette={"Male": "b", "Female": "y"})
    sns.despine(left=True)
    plt.show()

In [ ]:
sns.set()

# Load the example flights dataset and convert to long-form
flights_long = sns.load_dataset("flights")
flights = flights_long.pivot("month", "year", "passengers")

# Draw a heatmap with the numeric values in each cell
sns.heatmap(flights, annot=True, fmt="d", linewidths=.5)
plt.show()

In [ ]:
sns.set(style="darkgrid")

tips = sns.load_dataset("tips")
g = sns.FacetGrid(tips, row="sex", col="time", margin_titles=True)
bins = np.linspace(0, 60, 13)
g.map(plt.hist, "total_bill", color="steelblue", bins=bins, lw=0)
plt.show()

In [ ]:
sns.set(style="ticks")

# Create a dataset with many short random walks
rs = np.random.RandomState(4)
pos = rs.randint(-1, 2, (20, 5)).cumsum(axis=1)
pos -= pos[:, 0, np.newaxis]
step = np.tile(range(5), 20)
walk = np.repeat(range(20), 5)
df = pd.DataFrame(np.c_[pos.flat, step, walk],
                  columns=["position", "step", "walk"])

# Initialize a grid of plots with an Axes for each walk
grid = sns.FacetGrid(df, col="walk", hue="walk", col_wrap=5, height=1.5)

# Draw a horizontal line to show the starting point
grid.map(plt.axhline, y=0, ls=":", c=".5")

# Draw a line plot to show the trajectory of each random walk
grid.map(plt.plot, "step", "position", marker="o", ms=4)

# Adjust the tick positions and labels
grid.set(xticks=np.arange(5), yticks=[-3, 3],
         xlim=(-.5, 4.5), ylim=(-3.5, 3.5))

# Adjust the arrangement of the plots
grid.fig.tight_layout(w_pad=1)
plt.show()

# ======= Exercises =======

## Numpy exercises

The following short exercises test your understanding of simple numpy functions and objects. Make sure you can complete them and feel free to reference the official [documentation](http://docs.scipy.org/doc/) should you need it.

**You may need to google some solutions**

#### ========== Question 1 ==========
Print your numpy version.

In [11]:
# Your Code goes here:
np.__version__

'1.20.1'

#### ========== Question 2 ==========
Create a zero vector of size 5.

In [13]:
# Your Code goes here:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#### ========== Question 3 ==========
Create a zero vector of size 5 of type integer. Set the third element to 1.

In [20]:
# Your Code goes here:
a = np.zeros(5, dtype = int)
a[2] = 1
a

array([0, 0, 1, 0, 0])

#### ========== Question 4 ==========
Create a vector ranging from 0 to 9. 

In [27]:
# Your Code goes here:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### ========== Question 5 ==========
Create a vector ranging from 10 to 29.

In [26]:
# Your Code goes here:
np.arange(10,30)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

#### ========== Question 6 ==========
Create a vector ranging from 0 to 9 and reverse it.

In [30]:
# Your Code goes here:
c = np.arange(10)
c[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### ========== Question 7 ==========
Create a 5 x 3 zero matrix.

In [32]:
# Your Code goes here:
np.zeros(15).reshape(5,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### ========== Question 8 ==========
Create this matrix...without copy pasting it ;)
```
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])
```

In [34]:
# Your Code goes here:
np.arange(9).reshape(3,3).T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

#### ========== Question 9 ==========
Create a 3 X 3 identity matrix.

In [35]:
# Your Code goes here:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### ========== Question 10 ==========
Create a 2 X 2 X 2 array with random values (drawn from a normal distribution).

In [38]:
# Your Code goes here:
np.random.normal(0,1,(3,2))

array([[ 0.0675962 ,  0.17745775],
       [ 1.83047412,  0.00844002],
       [ 0.56416914, -0.38954206]])

#### ========== Question 11a ==========
Create a 5 x 4 array with random values and find the minimum and maximum values.

In [54]:
# Your Code goes here:
d = np.random.rand(5,4)
maximum = np.amax(d)
minimum = np.amin(d)
print('Max = ' + str(maximum) + ', Min = ' + str(minimum))

Max = 0.9892247469214626, Min = 0.11024115855118188


#### ========== Question 11b ==========
Return the *index* (i.e. the location within the matrix) of the max or min values

In [61]:
# Your Code goes here:
np.where(d == maximum)
np.where(d == minimum)

(array([2]), array([3]))

#### ========== Question 12 ==========
Find the mean value of the array in 11.

In [63]:
# Your Code goes here:
np.mean(d)

0.6079012762343003

#### ========== Question 13 ==========
Find the row means of the array in 11.

In [66]:
# Your Code goes here:
np.mean(d, axis = 0)

array([0.57577483, 0.57170106, 0.65376284, 0.63036638])

#### ========== Question 14 ==========
Find the column means of the array in 11.

In [67]:
# Your Code goes here:
np.mean(d, axis = 1)

array([0.72459886, 0.67000619, 0.46766579, 0.51884015, 0.65839539])

#### ========== Question 15 ==========
Create a list with elements 2.2, 3.5, 0, 4, 0. and convert into numpy array. Find the indices of non-zero elements.

In [74]:
# Your Code goes here:
a_list = [2.2,3.5,0,4,0]
f = np.array(a_list)
np.where(f != 0)

(array([0, 1, 3]),)

#### ========== Question 16 ==========
Crate two normally distributed random matrices of shape (5, 4) and (4, 2). Print their matrix product.

In [78]:
# Your Code goes here:
x = np.random.normal(0,1,(5,4))
z = np.random.normal(0,1,(4,2))
x.dot(z)

array([[ 2.10551941, -1.29065971],
       [ 0.92600496,  0.00865851],
       [ 1.21617696, -2.72251645],
       [ 0.15724546, -1.46698539],
       [ 2.42494564, -3.39007265]])

#### ========== Question 17 ==========
Crate a random matrix of shape (5, 3) and a random vector of size 3. Use broadcasting to add the two arrays.

In [80]:
# Your Code goes here:
t = np.random.rand(5,3)
h = np.random.rand(3)
t + h

array([[1.77009487, 1.06823749, 0.88668288],
       [0.97898252, 0.40137284, 0.9666113 ],
       [1.14127906, 1.07165764, 1.25062478],
       [1.5083757 , 0.81495542, 1.05540403],
       [1.20813052, 0.41113259, 0.9686731 ]])

## Pandas exercises

#### ========== Question 18 ==========
Load the `credit` dataset and display the dataset basic information.

In [86]:
# Your Code goes here:
credit_loc = os.path.join(os.getcwd(), 'datasets', 'credit.csv')
credit = pd.read_csv(credit_loc)
credit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   CheckingAccount   1001 non-null   object 
 1   Duration          1001 non-null   float64
 2   CreditHistory     1001 non-null   object 
 3   Purpose           1001 non-null   object 
 4   CreditAmount      1001 non-null   float64
 5   SavingsAccount    1001 non-null   object 
 6   YearsEmployed     1001 non-null   object 
 7   InstallmentRate   1001 non-null   float64
 8   PersonalStatus    1001 non-null   object 
 9   OtherDebtors      1001 non-null   object 
 10  ResidentSince     1001 non-null   float64
 11  Property          1001 non-null   object 
 12  Age               1001 non-null   float64
 13  OtherPlans        1001 non-null   object 
 14  Housing           1001 non-null   object 
 15  NumCreditsAtBank  1001 non-null   float64
 16  Job               1001 non-null   object 


#### ========== Question 19 ==========
Display the summary statistics of the attributes of the dataset.

In [87]:
# Your Code goes here:
credit.describe()

Duration  CreditAmount  InstallmentRate  ResidentSince          Age  \
count  1001.000000  1.001000e+03      1001.000000    1001.000000  1001.000000   
mean     20.882118 -9.957330e+05        -7.019980       2.842158    35.217782   
std      12.070878  3.160708e+07       316.165715       1.106825    15.398264   
min       0.000000 -1.000000e+09    -10000.000000       0.000000  -293.000000   
25%      12.000000  1.364000e+03         2.000000       2.000000    27.000000   
50%      18.000000  2.319000e+03         3.000000       3.000000    33.000000   
75%      24.000000  3.972000e+03         4.000000       4.000000    42.000000   
max      72.000000  1.842400e+04         4.000000       4.000000    75.000000   

       NumCreditsAtBank   Dependents  
count       1001.000000  1001.000000  
mean           0.406593     0.969031  
std           31.656714     5.894916  
min        -1000.000000  -185.000000  
25%            1.000000     1.000000  
50%            1.000000     1.000000  
75%            2.000000     1.000000  
max            4.000000     2.000000

#### ========== Question 20 ==========
Display the last 6 instances of the dataset.

In [88]:
# Your Code goes here:
credit.tail(6)

CheckingAccount  Duration CreditHistory     Purpose  CreditAmount  \
995             none      12.0    ok_til_now     car_new        2390.0   
996             none      12.0    ok_til_now   furniture        1736.0   
997               <0      30.0    ok_til_now    car_used        3857.0   
998             none      12.0    ok_til_now  television         804.0   
999               <0      45.0    ok_til_now  television        1845.0   
1000            <200      45.0      critical    car_used        4576.0   

     SavingsAccount YearsEmployed  InstallmentRate PersonalStatus  \
995         unknown           >=7              4.0    male_single   
996            <100            <7              3.0         female   
997            <100            <4              4.0  male_divorced   
998            <100           >=7              4.0    male_single   
999            <100            <4              4.0    male_single   
1000           <500    unemployed              3.0    male_single   

     OtherDebtors  ...     Property   Age  OtherPlans Housing  \
995          none  ...          car  50.0        none     own   
996          none  ...  real_estate  31.0        none     own   
997          none  ...      savings  40.0        none     own   
998          none  ...          car  38.0        none     own   
999          none  ...      unknown  23.0        none    free   
1000         none  ...          car  27.0        none     own   

     NumCreditsAtBank         Job Dependents  Telephone Foreign Approve  
995               1.0     skilled        1.0        yes     yes    good  
996               1.0   unskilled        1.0         no     yes    good  
997               1.0  management        1.0        yes     yes    good  
998               1.0     skilled        1.0         no     yes    good  
999               1.0     skilled        1.0        yes     yes     bad  
1000              1.0     skilled        1.0         no     yes    good  

[6 rows x 21 columns]

#### ========== Question 21 ==========
Print the 5th observation

In [93]:
# Your Code goes here:
credit[5:6]

CheckingAccount  Duration CreditHistory  Purpose  CreditAmount  \
5              <0      24.0   past_delays  car_new        4870.0   

  SavingsAccount YearsEmployed  InstallmentRate PersonalStatus OtherDebtors  \
5           <100            <4              3.0    male_single         none   

   ...  Property   Age  OtherPlans Housing NumCreditsAtBank      Job  \
5  ...   unknown  53.0        none    free              2.0  skilled   

  Dependents  Telephone Foreign Approve  
5        2.0         no     yes     bad  

[1 rows x 21 columns]

#### ========== Question 22 ==========
Print the standard deviation of the attribute `CreditAmount` by using the numpy method `std`. You can verify you get the correct result by inspecting the statistics table from Question 19.

In [96]:
# Your Code goes here:
credit['CreditAmount'].std()

31607080.582546458

## Matplotlib exercises

#### ========== Question 23 ==========
Initialise an empty figure of size (8,6). Create a scatter plot of the observations in the `credit` dataset for the attributes `Duration` and `Age` (age should be shown on the xaxis). Use black coloured markers. Label the axes accordingly by using red colour for the xaxis and green for the yaxis. Finally, add a title of your choice by using a font size of 20. 

In [ ]:
# Your Code goes here:

#### ========== Question 24 ==========
You should note above that there is an outlier (i.e. an observation that is very distant to the other observations). Now you think that there must be something wrong with that observation (why?) and as a next step you should remove it from both the age and duration variables and a make a scatter plot of the new data.

In [ ]:
# Your Code goes here: